
def get_us_states():
    states = [
        {'state_name': 'Alabama', 'state_code': 'AL'},
        {'state_name': 'Alaska', 'state_code': 'AK'},
        {'state_name': 'Alberta', 'state_code': 'AB'},
        {'state_name': 'American Samoa', 'state_code': 'AS'},
        {'state_name': 'Arizona', 'state_code': 'AZ'},
        {'state_name': 'Arkansas', 'state_code': 'AR'},
        {'state_name': 'Armed Forces (AE)', 'state_code': 'AE'},
        {'state_name': 'Armed Forces Americas', 'state_code': 'AA'},
        {'state_name': 'Armed Forces Pacific', 'state_code': 'AP'},
        {'state_name': 'British Columbia', 'state_code': 'BC'},
        {'state_name': 'California', 'state_code': 'CA'},
        {'state_name': 'Colorado', 'state_code': 'CO'},
        {'state_name': 'Connecticut', 'state_code': 'CT'},
        {'state_name': 'Delaware', 'state_code': 'DE'},
        {'state_name': 'District Of Columbia', 'state_code': 'DC'},
        {'state_name': 'Florida', 'state_code': 'FL'},
        {'state_name': 'Georgia', 'state_code': 'GA'},
        {'state_name': 'Guam', 'state_code': 'GU'},
        {'state_name': 'Hawaii', 'state_code': 'HI'},
        {'state_name': 'Idaho', 'state_code': 'ID'},
        {'state_name': 'Illinois', 'state_code': 'IL'},
        {'state_name': 'Indiana', 'state_code': 'IN'},
        {'state_name': 'Iowa', 'state_code': 'IA'},
        {'state_name': 'Kansas', 'state_code': 'KS'},
        {'state_name': 'Kentucky', 'state_code': 'KY'},
        {'state_name': 'Louisiana', 'state_code': 'LA'},
        {'state_name': 'Maine', 'state_code': 'ME'},
        {'state_name': 'Manitoba', 'state_code': 'MB'},
        {'state_name': 'Maryland', 'state_code': 'MD'},
        {'state_name': 'Massachusetts', 'state_code': 'MA'},
        {'state_name': 'Michigan', 'state_code': 'MI'},
        {'state_name': 'Minnesota', 'state_code': 'MN'},
        {'state_name': 'Mississippi', 'state_code': 'MS'},
        {'state_name': 'Missouri', 'state_code': 'MO'},
        {'state_name': 'Montana', 'state_code': 'MT'},
        {'state_name': 'Nebraska', 'state_code': 'NE'},
        {'state_name': 'Nevada', 'state_code': 'NV'},
        {'state_name': 'New Brunswick', 'state_code': 'NB'},
        {'state_name': 'New Hampshire', 'state_code': 'NH'},
        {'state_name': 'New Jersey', 'state_code': 'NJ'},
        {'state_name': 'New Mexico', 'state_code': 'NM'},
        {'state_name': 'New York', 'state_code': 'NY'},
        {'state_name': 'Newfoundland', 'state_code': 'NF'},
        {'state_name': 'North Carolina', 'state_code': 'NC'},
        {'state_name': 'North Dakota', 'state_code': 'ND'},
        {'state_name': 'Northwest Territories', 'state_code': 'NT'},
        {'state_name': 'Nova Scotia', 'state_code': 'NS'},
        {'state_name': 'Nunavut', 'state_code': 'NU'},
        {'state_name': 'Ohio', 'state_code': 'OH'},
        {'state_name': 'Oklahoma', 'state_code': 'OK'},
        {'state_name': 'Ontario', 'state_code': 'ON'},
        {'state_name': 'Oregon', 'state_code': 'OR'},
        {'state_name': 'Pennsylvania', 'state_code': 'PA'},
        {'state_name': 'Prince Edward Island', 'state_code': 'PE'},
        {'state_name': 'Puerto Rico', 'state_code': 'PR'},
        {'state_name': 'Quebec', 'state_code': 'QC'},
        {'state_name': 'Rhode Island', 'state_code': 'RI'},
        {'state_name': 'Saskatchewan', 'state_code': 'SK'},
        {'state_name': 'South Carolina', 'state_code': 'SC'},
        {'state_name': 'South Dakota', 'state_code': 'SD'},
        {'state_name': 'Tennessee', 'state_code': 'TN'},
        {'state_name': 'Texas', 'state_code': 'TX'},
        {'state_name': 'Utah', 'state_code': 'UT'},
        {'state_name': 'Vermont', 'state_code': 'VT'},
        {'state_name': 'Virgin Islands', 'state_code': 'VI'},
        {'state_name': 'Virginia', 'state_code': 'VA'},
        {'state_name': 'Washington', 'state_code': 'WA'},
        {'state_name': 'West Virginia', 'state_code': 'WV'},
        {'state_name': 'Wisconsin', 'state_code': 'WI'},
        {'state_name': 'Wyoming', 'state_code': 'WY'},
        {'state_name': 'Yukon Territory', 'state_code': 'YT'}
    ]

    for data in states:
        print(data)

    return states
